### ISSUE TITLE
restore() not working with Meteor

### ISSUE THREAD

**Issue by osamakhn** [hwillson/meteor-stub-collections#5]
Doing nothing but just following the example code leaves a record in the MongoCollection instead of not writing it in the first place or at worst deleting it when restore() is called. Has there been a breaking update to sinon#sandbox causing this?

**Comment by hwillson** [comment]
@osamakhn Which example code are you following? The tests are passing which verify that the proper stubbed out in memory Collection is used, and the real Collection isn't touched. Can you provide more details?

**Comment by hwillson** [comment]
I'll close this off for now - please post back with the previously requested details, if this is still happening.
